### ISSUE TITLE
Are examples still working?

### ISSUE THREAD

**Issue by manuscle** [jifalops/mdc_web#1]
Hi, I try to reproduce the example but I got an error when I try to import styles to my styles.scss file

Error: Can't find stylesheet to import.
@import "material-components-web/material-components-web";

EDIT: I forgot to install node package so I did it, I've also added your version of sass_builder into pubspec.yaml but I'm getting the following when I pub get:
Because every version of sass_builder from git depends on build ^0.12.5 and build_runner 1.1.2 depends on build >=1.0.0 <1.1.0, sass_builder from git is incompatible with build_runner 1.1.2.
And because no versions of build_runner match >1.1.2 <2.0.0, sass_builder from git is incompatible with build_runner ^1.1.2.

**Comment by jifalops** [comment]
Yes they still work. From the example/web/web directory, type `npm install`
into the console. That should fix that error.

**Comment by manuscle** [comment]
I resolved the npm error, see my edit part of my message
I need your sass builder fork working in my app but I get compatibility issues

**Comment by jifalops** [comment]
@manuscle Try again, the dependency has been changed.

**Comment by manuscle** [comment]
Thank you!
Now I can't resolve this dependency error:
Because angular_components 0.10.1 depends on sass_builder ^2.0.2 and no versions of angular_components match >0.10.1 <0.11.0, angular_components ^0.10.1 requires sass_builder from hosted.
So, because agde_mobilite_web depends on both angular_components ^0.10.1 and sass_builder from git, version solving failed.

But maybe if I use mdc_web, I don't need angular_components anymore?

**Comment by jifalops** [comment]
Yes if you use mdc_web you don't need angular_components any more. My fork of `sass_builder` has the same version number that it was forked from, so I'm not sure why there'd be an issue there.

**Comment by manuscle** [comment]
Ok I'll play a while with.
Thanks for help!
